window.AXM_STUDIO_STATE = Object.freeze({
  recordedAt: "2026-09-20T00:37:31Z",
  controlRoomHead: "f742ed67478ada463eee098909e8943958558209",
  truthBoundary:
    "Read-only convergence view. A visible preview does not promote a candidate, close a gate, or transfer domain authority.",
  domains: [
    {
      id: "character",
      name: "Character",
      repo: "axm-character-design",
      owner: "Organic Form → Geometry → Rigging → Animation",
      state: "hold",
      label: "Visual gate",
      source: "PR #22 · 5513ab66372ee06ce53788f5097ede230ca2fc6b",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-character-design/pull/22",
      preview: "assets/previews/character.png",
      summary: "Review006 shoulder form and bounded motion samples.",
      capability: "A connected, deforming shoulder candidate with retained target-host evidence.",
      blocker: "Independent motion/shading acceptance and target-device runtime remain open.",
      next: "Review the exact motion visually, then run target-device runtime without retuning unrelated geometry.",
      dependsOn: ["Universal Creation observers"],
      proof: "Exact generated geometry inspection; not a fresh Godot acceptance capture.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-character-design"
    },
    {
      id: "animal",
      name: "Animal",
      repo: "axm-animal-design",
      owner: "Organic Form → Geometry → Rigging → Materials",
      state: "hold",
      label: "Rebind + visual",
      source: "PR #24 · 5240e905f949a7557e95b4ec598624c9df2eebd7",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-animal-design/pull/24",
      preview: "assets/previews/animal.png",
      summary: "Bilateral forelimb and tangent-frame deformation candidate.",
      capability: "Connected forelimb geometry survives representative bounded deformation checks.",
      blocker: "Animation and Runtime still consume an older owner identity.",
      next: "Rebind Animation/Runtime to current Rigging, then rerun deformation, visual, and device gates.",
      dependsOn: ["Current Rigging owner", "31-key runtime candidate"],
      proof: "Exact candidate geometry inspection; final creature art is not claimed.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-animal-design"
    },
    {
      id: "nature",
      name: "Nature",
      repo: "axm-nature-design",
      owner: "Organic Form → Geometry → Rigging → Procedural",
      state: "hold",
      label: "Junction blocked",
      source: "PR #30 · 8ab552710df21567cfd601af99181918e2cfadb3",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-nature-design/pull/30",
      preview: "assets/previews/nature.png",
      summary: "East-rear tree source and indexed north-low diagnostic.",
      capability: "The exact source surface can locate the indexed opening without pretending the junction exists.",
      blocker: "The connected branch/trunk cut and junction are not authored or proven.",
      next: "Resolve the junction in Geometry, then rebind Rigging → Animation/VFX → Technical Art → Map.",
      dependsOn: ["Weather response", "Map receiving slot"],
      proof: "Source mesh plus indexed-surface PASS/HOLD receipt.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-nature-design"
    },
    {
      id: "object",
      name: "Object",
      repo: "axm-object-design",
      owner: "Hard Surface → Rigging → Technical Art",
      state: "hold",
      label: "TA rebind",
      source: "PR #23 · e5d4102b0b675cc0dc74d65f7afce1bdbf448726",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-object-design/pull/23",
      preview: "assets/previews/object.png",
      summary: "Modular equipment case with source-owned latch hardware.",
      capability: "A generated structural case with explicit hinges, sockets, latch ownership, and rig binding.",
      blocker: "Technical Art keeper-seat/source authority is stale; downstream consumers inherit that break.",
      next: "Repair the keeper-seat gate, then rebind Animation, Technical Art, Runtime, and Map upstream-first.",
      dependsOn: ["Universal Creation scene graph", "Map service clearance"],
      proof: "Structural mesh PASS: 468 vertices, 812 triangles; motion/material acceptance remains open.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-object-design"
    },
    {
      id: "building",
      name: "Building",
      repo: "axm-building-design",
      owner: "Hard Surface → Geometry → Procedural → Materials",
      state: "accepted",
      label: "Accepted main",
      source: "main · 0df875379df67d7d940accc98c61e6071b733a65",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-building-design/commit/0df875379df67d7d940accc98c61e6071b733a65",
      preview: "assets/previews/building.png",
      summary: "Service pavilion with source-bound geometry, procedural assembly, and a verified five-material packet.",
      capability: "Merged source, topology, procedural, Materials, and first deterministic AI-callable specialist tool line.",
      blocker: "Final aesthetic acceptance, environment adoption, and target-device Runtime remain open.",
      next: "Expose the exact tool receipt here, then let Map and Runtime consume this identity without changing Building authority.",
      dependsOn: ["Sticker Fabric neutral frame helper"],
      proof: "190 exact-donor tests with zero skips plus exact-head Godot 4.7.2 A/B render; structural scope only.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-building-design"
    },
    {
      id: "map",
      name: "Map",
      repo: "axm-map-design",
      owner: "Environment / World Art",
      state: "hold",
      label: "Stale donors",
      source: "PR #24 · 061dbf12604f8a4ee19a62a79f0d9d2f99503181",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-map-design/pull/24",
      preview: "assets/previews/map.png",
      summary: "First environment slice combining weather and specialist sources.",
      capability: "A 17-state path-eye/elevated composition exists and can be reconstructed exactly.",
      blocker: "It still binds older Building, Weather, Nature, and Object identities.",
      next: "Rebind the accepted Building/Weather mains and current Object/Nature owners, then rerun visual/runtime gates.",
      dependsOn: ["Building", "Weather", "Nature", "Object"],
      proof: "Exact PR #24 structural reconstruction PASS; current-world acceptance is not claimed.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-map-design"
    },
    {
      id: "weather",
      name: "Weather",
      repo: "axm-weather-design",
      owner: "VFX / Atmosphere → Procedural",
      state: "accepted",
      label: "Accepted main",
      source: "main · be6ea1991435d7bcf1d35af29199bbb4b2e779f4",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-weather-design/commit/be6ea1991435d7bcf1d35af29199bbb4b2e779f4",
      preview: "assets/previews/weather.png",
      summary: "Deterministic wind-field baseline and three-seed family.",
      capability: "Bounded, repeatable atmospheric streak layouts with exact visual-direction movement.",
      blocker: "Physical weather, environment art acceptance, and target-device runtime are outside the accepted claim.",
      next: "Consume the accepted source identity in Map without expanding its truth boundary.",
      dependsOn: [],
      proof: "Current main baseline and variation-family checks PASS; repository-native SVG coordinates shown.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-weather-design"
    },
    {
      id: "universal-creation",
      name: "Universal Creation",
      repo: "axm-universal-creation",
      owner: "Generic capability provider",
      state: "support",
      label: "Current provider",
      source: "main · 9381bd850a32c9c76a9aff4a04d4687f5a87b1ae",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-universal-creation/commit/9381bd850a32c9c76a9aff4a04d4687f5a87b1ae",
      preview: "assets/previews/universal-creation.png",
      summary: "Current shared provider identity with representative retained output.",
      capability: "Directional texel-density and opt-in closed-shell orientation observation.",
      blocker: "Newer UC lanes exist on main, but no Studio domain has rebound to or adopted them here.",
      next: "Remain an optional observer; add no domain semantics for shell convenience.",
      dependsOn: [],
      proof: "Exact current main identity; preview remains representative and no new Studio capability was promoted.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-universal-creation"
    },
    {
      id: "weapon",
      name: "Weapon",
      repo: "axm-weapon-design",
      owner: "Domain owner",
      state: "empty",
      label: "No visual lane",
      source: "main · fac273a6f2d752347b65927f944200f231af11db",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-weapon-design/commit/fac273a6f2d752347b65927f944200f231af11db",
      summary: "Repository exists, but current main has no standalone visual artifact.",
      capability: "No convergence capability claimed.",
      blocker: "No active evidence-cleared lineage exists.",
      next: "Wait for a real product requirement before starting a lane.",
      dependsOn: [],
      proof: "Absence is shown rather than filled with invented work.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-weapon-design"
    },
    {
      id: "armor",
      name: "Armor",
      repo: "axm-armor-design",
      owner: "Domain owner",
      state: "empty",
      label: "No visual lane",
      source: "main · 57260d53977184bad70ef1e3af887f97d0f149d4",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-armor-design/commit/57260d53977184bad70ef1e3af887f97d0f149d4",
      summary: "Repository exists, but current main has no standalone visual artifact.",
      capability: "No convergence capability claimed.",
      blocker: "No active evidence-cleared lineage exists.",
      next: "Wait for a real product requirement before starting a lane.",
      dependsOn: [],
      proof: "Absence is shown rather than filled with invented work.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-armor-design"
    },
    {
      id: "unit",
      name: "Unit",
      repo: "axm-unit-design",
      owner: "Unassigned",
      state: "empty",
      label: "Empty repository",
      source: "no source commit",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-unit-design",
      summary: "No source identity currently exists.",
      capability: "Nothing to integrate.",
      blocker: "The repository is empty.",
      next: "Do not invent a unit system until a product needs ownership beyond Character/Animal/Vehicle.",
      dependsOn: [],
      proof: "Repository state only.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-unit-design"
    },
    {
      id: "misc",
      name: "Misc",
      repo: "axm-misc-design",
      owner: "Fallback domain",
      state: "empty",
      label: "No visual lane",
      source: "main · d8650bc792eaf86c2f864d75cbac89e80ec8aa3c",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-misc-design/commit/d8650bc792eaf86c2f864d75cbac89e80ec8aa3c",
      summary: "No standalone current visual artifact.",
      capability: "No convergence capability claimed.",
      blocker: "No active evidence-cleared lineage exists.",
      next: "Keep this from becoming a dumping ground; assign future work to a named owner when possible.",
      dependsOn: [],
      proof: "Repository state only.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-misc-design"
    },
    {
      id: "profession-fabric",
      name: "Profession Fabric",
      repo: "axm-profession-fabric",
      owner: "Reusable procedure provider",
      state: "support",
      label: "Retest hold",
      source: "main · 941bd05007eb5cd88e773e66c858c62cf9de38a9",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-profession-fabric/commit/941bd05007eb5cd88e773e66c858c62cf9de38a9",
      summary: "Contracts and specialist procedures; not a domain asset repository.",
      capability: "Candidate home for reusable evidence procedures.",
      blocker: "PRs #35/#37 need exact-head retest and cross-domain proof.",
      next: "Retest without promoting domain assets or automatic authority.",
      dependsOn: ["Cross-domain evidence"],
      proof: "Procedure state only; no standalone 3D scene.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-profession-fabric"
    },
    {
      id: "wreckline",
      name: "Wreckline",
      repo: "axm-wreckline",
      owner: "Product receiver",
      state: "hold",
      label: "Dependency blocked",
      source: "main · 22b8d1c0cf5f08c030e7db36c56eaac84c7c1650",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-wreckline/commit/22b8d1c0cf5f08c030e7db36c56eaac84c7c1650",
      summary: "Product receiver with stale providers and missing historical UC capabilities.",
      capability: "Retained vertical-slice and vehicle evidence only.",
      blocker: "PRs #3–#5 use stale providers; #6/#8 require absent UC providers.",
      next: "Repair provider identities before any product-level promotion.",
      dependsOn: ["Vehicle ownership", "UC provider repair"],
      proof: "Blocked lineage record; no accepted current-shell preview.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-wreckline"
    },
    {
      id: "sticker-fabric",
      name: "Sticker Fabric",
      repo: "axm-sticker-fabric",
      owner: "Neutral transform donor",
      state: "support",
      label: "Donor only",
      source: "main · 3aa93b0132eea9becefb20c716c6ec1a023ad28b",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-sticker-fabric/commit/3aa93b0132eea9becefb20c716c6ec1a023ad28b",
      summary: "Supplies Building's pinned neutral rigid-frame helper.",
      capability: "One exact generic transform contract used by Building.",
      blocker: "Its independent growth lanes are outside this Studio convergence scope.",
      next: "Keep donor use thin; do not import unrelated Sticker Fabric growth.",
      dependsOn: [],
      proof: "Exact donor identity verified by Building's integrated gate.",
      repoUrl: "https://github.com/mike-axiom-mir/axm-sticker-fabric"
    }
  ],
  tools: [
    {
      id: "building-materials-packet",
      toolId: "axm.building.materials.packet",
      name: "Building Materials Packet",
      status: "AI_CALLABLE",
      owner: "Materials / LookDev",
      repo: "axm-building-design",
      source: "main · 0df875379df67d7d940accc98c61e6071b733a65",
      sourceHead: "0df875379df67d7d940accc98c61e6071b733a65",
      verifiedHead: "496c5a070b56acad7c319bc52caf0d52679c5b00",
      sourceUrl: "https://github.com/mike-axiom-mir/axm-building-design/commit/0df875379df67d7d940accc98c61e6071b733a65",
      manifestPath: "tooling/building-materials-packet.manifest.json",
      manifestBlob: "bc1889a08379fcc319a2891164269d68190ea0ff",
      manifestUrl: "https://github.com/mike-axiom-mir/axm-building-design/blob/0df875379df67d7d940accc98c61e6071b733a65/tooling/building-materials-packet.manifest.json",
      workflowUrl: "https://github.com/mike-axiom-mir/axm-building-design/actions/runs/35477806689",
      evidenceScopes: ["structural"],
      layers: {
        ai: "verified",
        human: "absent",
        intent: "absent"
      },
      command: "python tools/run_building_materials_tool.py --request <request.json>",
      request: ["exact Building source identity", "material profile", "topology role bindings"],
      result: ["deterministic material packet", "source-bound receipt", "validation or explicit HOLD"],
      plan: [
        "Read the owner manifest and verify its exact blob identity.",
        "Bind the request to the accepted Building source head.",
        "Route execution to axm-building-design; Create-Me does not execute it.",
        "Read the structural receipt and preserve any HOLD condition.",
        "Route visual, environment, and runtime gates to their owners."
      ],
      owns: ["bounded material values", "surface assignments", "packet and receipt schema"],
      doesNotOwn: ["Building source geometry", "art-direction acceptance", "environment adoption", "target-device runtime"],
      holdConditions: ["source identity mismatch", "dirty source tree", "profile or topology validation failure"],
      nonclaims: ["No final visual acceptance", "No physical-material validation", "No environment or gameplay adoption", "No production device acceptance"],
      proof: "190 exact-donor tests passed with zero skips; exact-head Godot 4.7.2 A/B render passed at workflow run 35477806689.",
      executionOwnerRepo: "axm-building-design",
      createMeCanExecute: false
    }
  ],
  seats: [
    ["3D Art Director", "01_3d_art_director.md"],
    ["Geometry / Topology", "02_geometry_topology.md"],
    ["Hard Surface", "03_hard_surface.md"],
    ["Organic Form", "04_organic_form.md"],
    ["Materials / LookDev", "05_materials_lookdev.md"],
    ["Rigging / Deformation", "06_rigging_deformation.md"],
    ["Animation / Motion", "07_animation_motion.md"],
    ["Environment / World Art", "08_environment_world_art.md"],
    ["VFX / Atmosphere", "09_vfx_atmosphere.md"],
    ["Procedural Design", "10_procedural_design.md"],
    ["Technical Art / UC", "11_technical_art_uc_integration.md"],
    ["Runtime Optimization", "12_runtime_optimization.md"],
    ["Visual Observer / QA", "13_visual_observer_qa.md"],
    ["Capability Cartographer", "14_capability_cartographer.md"]
  ]
});
